### GET request to flickr api
GET http://localhost:3000/api/flickr
Accept: application/json

###
GET http://localhost:3000/api/flickr?query=cover&items=50
Accept: application/json

###
GET http://localhost:3000/api/flickr?query=boudoir
Accept: application/json

###
GET http://localhost:3000/api/flickr?query=delaiagonzalez&items=9
Accept: application/json
###

POST http://localhost:3000/api/contact
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name = John Doe &
email = johndoe@example.com &
 message = Hello, I am John Doe