import Hero from "@/components/Hero";
import SocialMedia from "@/components/SocialMedia";
import Gallery from "@/components/Gallery";
import ContactForm from "@/components/ContactForm";
import type { Metadata } from "next";
import { getFlickrPhotos } from "@/services/getFlickrPhotos";

export const metadata: Metadata = {
  title: "Boudoir Barcelona",
  description: "Generated by create next app",
};

export default async function HomePage() {
  const res = await getFlickrPhotos();

  if (!res.success) {
    return <div>Error: {res.reason}</div>;
  }

  return (
    <main className={"dark:bg-gray-900 dark:text-white bg-white text-gray-900"}>
      {/* Hero Section with Parallax */}
      <Hero />

      {/* Social Media Links */}
      <SocialMedia />

      {/* Gallery Section with Pinterest-like layout */}
      <Gallery photos={res.photos} />

      {/* Contact Form Section */}
      <ContactForm />
    </main>
  );
}
